### ISSUE TITLE
I don't have a H drive

### ISSUE THREAD

**Issue by dwijtsma** [tsworman/TortoiseGit-ExcelComparison#1]
A temporary file is created at the H drive (line 29), maybe better to do that at drive C, which every Windows user has. On my PC the script failed because of that.

At line 40 you should reference to the variable 'sTempFile' instead of typing the filename again. It should be as following:
`result = WshShell.Run("""C:\Program Files (x86)\Microsoft Office\Office16\DCF\SPREADSHEETCOMPARE.exe"" " & sTempFile, 0, True)`

Thanks for the script. I'm using it i.c.w. TortoiseSVN 1.8.8

**Comment by tsworman** [comment]
@fuaim Thanks for the feedback! I believe I resolved all the issues and updated the repository. Thanks for opening the issue. Glad the tool was able to help you out.
