### ISSUE TITLE
How to get it compatible with Office 365

### ISSUE THREAD

**Issue by dwijtsma** [tsworman/TortoiseGit-ExcelComparison#3]
With Office365 spreadsheetcompare.exe has been moved. Would be nice if the path was changed based on Office version installed. 
Modified line 50 to fix the script for me:
`result = WshShell.Run("""C:\Program Files\Microsoft Office\root\vfs\ProgramFilesX86\Microsoft Office\Office16\DCF\SPREADSHEETCOMPARE.EXE"" " & sTempFile, 0, True)`

**Comment by stuartmcgarrity** [comment]
This script is exactly what I was looking for. Thank you.

Similarly, I had to make one modification for my Spreadsheet Compare location: C:\Program Files (x86)\Microsoft Office\root\Office16\DCF\SPREADSHEETCOMPARE.exe

**Comment by tsworman** [comment]
Glad it worked for you both. I pushed @stuartmcgarrity's path into the code base and made of a note there as well of @dwijtsma's in case it varies by user.

I don't actively use this anymore but super excited to see it still be useful!
